package ru.itmo.mopsync.ruleengine.service;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import ru.itmo.mopsync.ruleengine.model.Alert;
import ru.itmo.mopsync.ruleengine.model.DeviceDataDocument;
import ru.itmo.mopsync.ruleengine.model.Rule;
import ru.itmo.mopsync.ruleengine.repository.AlertRepository;

import java.time.OffsetDateTime;

/**
 * Service for creating alert instances.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class AlertService {

    private final AlertRepository alertRepository;

    /**
     * Creates an alert instance when a rule is satisfied.
     *
     * @param rule       rule that was satisfied
     * @param deviceData device data package that satisfied the rule
     */
    public void createAlert(Rule rule, DeviceDataDocument deviceData) {
        Alert alert = new Alert(
                null, // ID will be generated by MongoDB
                rule.getId(),
                deviceData.getId(),
                OffsetDateTime.now()
        );

        Alert saved = alertRepository.save(alert);
        log.info("Created alert {} for rule {} and device data {}", saved.getId(), rule.getId(), deviceData.getId());
    }
}
