package ru.itmo.mopsync.iotcontroller.service;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import ru.itmo.mopsync.iotcontroller.generated.model.DeviceDataRequest;
import ru.itmo.mopsync.iotcontroller.model.DeviceDataDocument;
import ru.itmo.mopsync.iotcontroller.repository.DeviceDataRepository;

/**
 * Service for processing and persisting device data.
 * Validation is performed in the controller layer using JSR-303 annotations and custom Validator.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class DeviceDataService {

    private final DeviceDataRepository repository;
    private final RabbitMqMessageSender messageSender;

    /**
     * Processes device data: saves to MongoDB and sends notification to RabbitMQ.
     * Validation is assumed to be completed before this method is called.
     *
     * @param request device data request (already validated)
     */
    public void processDeviceData(DeviceDataRequest request) {
        log.debug("Processing device data for device: {}", request.getDeviceId());

        DeviceDataDocument document = createDocument(request);
        DeviceDataDocument saved = repository.save(document);
        log.debug("Saved device data with id: {}", saved.getId());

        messageSender.sendDeviceDataNotification(saved.getId());
        log.debug("Sent notification to RabbitMQ for device data id: {}", saved.getId());
    }

    /**
     * Creates a MongoDB document from the request.
     *
     * @param request device data request
     * @return document to save
     */
    private DeviceDataDocument createDocument(DeviceDataRequest request) {
        return new DeviceDataDocument(
                null, // ID will be generated by MongoDB
                request.getDeviceId(),
                request.getTimestamp(),
                request.getSeq(),
                request.getMetrics(),
                request.getMeta()
        );
    }
}
