filebeat.inputs:
  - type: filestream
    paths:
      - '/logs/data-simulator/server.json.log'
      - '/logs/data-simulator/server-*.json.log'
    fields:
      service: data-simulator
      env: prod
    fields_under_root: true

  - type: filestream
    paths:
      - '/logs/iot-controller/server.json.log'
      - '/logs/iot-controller/server-*.json.log'
    fields:
      service: iot-controller
      env: prod
    fields_under_root: true

  - type: filestream
    paths:
      - '/logs/rule-engine/server.json.log'
      - '/logs/rule-engine/server-*.json.log'
    fields:
      service: rule-engine
      env: prod
    fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]

processors:
  - add_host_metadata: {}
  - add_cloud_metadata: {}
