openapi: 3.0.3
info:
  title: Data Simulator API
  description: API for managing IoT data simulation
  version: 1.0.0

servers:
  - url: http://localhost:8080

tags:
  - name: simulation
    description: API for controlling data simulation

paths:
  /api/v1/simulation/start:
    post:
      summary: Start data simulation
      operationId: startSimulation
      tags:
        - simulation
      responses:
        200:
          description: Simulation started successfully
        400:
          description: Bad request - simulation already running or invalid state
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"

  /api/v1/simulation/stop:
    post:
      summary: Stop data simulation
      operationId: stopSimulation
      tags:
        - simulation
      responses:
        200:
          description: Simulation stopped successfully
        400:
          description: Bad request - simulation not running
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"

  /api/v1/simulation/spec:
    post:
      summary: Set simulation specification
      operationId: setSimulationSpec
      tags:
        - simulation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SimulationSpecRequest"
      responses:
        200:
          description: Specification set successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimulationSpecResponse"
        400:
          description: Bad request - invalid specification
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"

components:
  schemas:
    SimulationSpecRequest:
      description: Simulation specification with device groups
      type: object
      required:
        - groups
      properties:
        groups:
          type: array
          description: List of device groups to simulate
          items:
            $ref: "#/components/schemas/DeviceGroup"
          minItems: 1

    DeviceGroup:
      description: Configuration for a group of devices. Either metrics-template (predefined template name) or metrics (manual definition) must be provided.
      type: object
      required:
        - count
        - frequency
      properties:
        count:
          type: integer
          format: int32
          description: Number of devices in this group
          minimum: 1
        frequency:
          type: integer
          format: int32
          description: Number of packages generated by one device per day (24 hours)
          minimum: 1
        metrics-template:
          type: string
          description: Name of a predefined metrics template (e.g., "teapot", "lamp"). Either this or metrics field must be provided.
        metrics:
          type: object
          description: Manual definition of metrics structure for devices in this group. Either this or metrics-template field must be provided.
          additionalProperties:
            $ref: "#/components/schemas/MetricDefinition"

    MetricDefinition:
      description: Definition of a metric in the metrics template
      type: object
      required:
        - type
      properties:
        type:
          type: string
          description: Type of the metric value
          enum:
            - number
            - integer
            - string
        min:
          type: number
          format: double
          description: Minimum value (for number/integer types)
        max:
          type: number
          format: double
          description: Maximum value (for number/integer types)
        values:
          type: array
          description: List of possible values (for string type)
          items:
            type: string

    SimulationSpecResponse:
      description: Response containing the created simulation specification with device groups and their metrics description
      type: object
      required:
        - groups
      properties:
        groups:
          type: array
          description: List of created device groups with their metrics description
          items:
            $ref: "#/components/schemas/DeviceGroupResponse"
          minItems: 1

    DeviceGroupResponse:
      description: Response object describing a created device group and its metrics
      type: object
      required:
        - deviceIds
        - frequency
        - metrics
      properties:
        deviceIds:
          type: array
          description: List of IDs of created devices in this group
          items:
            type: string
          minItems: 1
        frequency:
          type: integer
          format: int32
          description: Number of packages generated by one device per day (24 hours)
          minimum: 1
        metrics:
          type: object
          description: Metrics definition for devices in this group (templates are resolved to metrics at creation time)
          additionalProperties:
            $ref: "#/components/schemas/MetricDefinition"

    ErrorObject:
      description: Error response object
      type: object
      properties:
        code:
          description: Numeric error code
          type: integer
          format: int32
        message:
          description: Unique text identifier of the error
          type: string
        humanMessage:
          description: Human-readable error description
          type: string

